baseURL = "https://depoze.xyz/"
title = "CuSO4_Deposit"
theme = "hugo-tufte"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

disableKinds = ["taxonomy", "term"]

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[params]
  math = true
  codeBlocksDark = false
  showPoweredBy = false

[languages]
  [languages.zh]
    label = "简体中文"
    locale = "zh-CN"
    weight = 1
  [languages.en]
    label = "English"
    locale = "en"
    weight = 2

[languages.zh.params]
  subtitle = "软件工程师，只有折腾数据的时候我感受到自己活着。"
[languages.en.params]
  subtitle = "Software Engineer. I feel alive when I'm wrangling data."

[languages.zh.menu]
  [[languages.zh.menu.nav]]
    name = "文字"
    url = "https://blog.depoze.xyz"
    weight = 1
[languages.en.menu]
  [[languages.en.menu.nav]]
    name = "Blog"
    url = "https://blog.depoze.xyz"
    weight = 1
