baseURL = "https://depoze.xyz/"
title = "CuSO4_Deposit"
enableRobotsTXT = true
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    noClasses = true

[params]
  math = true

[languages]
  [languages.zh]
    label = "简体中文"
    locale = "zh-CN"
    weight = 1
  [languages.en]
    label = "English"
    locale = "en"
    weight = 2

[languages.zh.params]
  subtitle = "软件工程师，只有折腾数据的时候我感受到自己活着。"
[languages.en.params]
  subtitle = "Software Engineer. I feel alive when I'm wrangling data."

[languages.zh.menu]
  [[languages.zh.menu.nav]]
    name = "文字"
    url = "/pages/"
    weight = 1
  [[languages.zh.menu.nav]]
    name = "友链"
    url = "/friends/"
    weight = 2
  [[languages.zh.menu.nav]]
    name = "用物"
    url = "/uses/"
    weight = 3
[languages.en.menu]
  [[languages.en.menu.nav]]
    name = "Blog"
    url = "/pages/"
    weight = 1
  [[languages.en.menu.nav]]
    name = "Friends"
    url = "/friends/"
    weight = 2
  [[languages.en.menu.nav]]
    name = "Uses"
    url = "/uses/"
    weight = 3
